//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WBS_LightForm01.WSService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BalanceFunctions_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions")]
    public partial class BalanceFunctions : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateCololerCodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFontCodesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BalanceFunctions() {
            this.Url = global::WBS_LightForm01.Properties.Settings.Default.WBS_LightForm01_WSService_BalanceFunctions;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCololerCodesCompletedEventHandler CreateCololerCodesCompleted;
        
        /// <remarks/>
        public event CreateFontCodesCompletedEventHandler CreateFontCodesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions:CreateCololerCodes", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions", ResponseElementName="CreateCololerCodes_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateCololerCodes(string vSCode, string vSDescription) {
            this.Invoke("CreateCololerCodes", new object[] {
                        vSCode,
                        vSDescription});
        }
        
        /// <remarks/>
        public void CreateCololerCodesAsync(string vSCode, string vSDescription) {
            this.CreateCololerCodesAsync(vSCode, vSDescription, null);
        }
        
        /// <remarks/>
        public void CreateCololerCodesAsync(string vSCode, string vSDescription, object userState) {
            if ((this.CreateCololerCodesOperationCompleted == null)) {
                this.CreateCololerCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCololerCodesOperationCompleted);
            }
            this.InvokeAsync("CreateCololerCodes", new object[] {
                        vSCode,
                        vSDescription}, this.CreateCololerCodesOperationCompleted, userState);
        }
        
        private void OnCreateCololerCodesOperationCompleted(object arg) {
            if ((this.CreateCololerCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCololerCodesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions:CreateFontCodes", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions", ResponseElementName="CreateFontCodes_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/BalanceFunctions", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateFontCodes(string vSCode, string vSDescription) {
            this.Invoke("CreateFontCodes", new object[] {
                        vSCode,
                        vSDescription});
        }
        
        /// <remarks/>
        public void CreateFontCodesAsync(string vSCode, string vSDescription) {
            this.CreateFontCodesAsync(vSCode, vSDescription, null);
        }
        
        /// <remarks/>
        public void CreateFontCodesAsync(string vSCode, string vSDescription, object userState) {
            if ((this.CreateFontCodesOperationCompleted == null)) {
                this.CreateFontCodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFontCodesOperationCompleted);
            }
            this.InvokeAsync("CreateFontCodes", new object[] {
                        vSCode,
                        vSDescription}, this.CreateFontCodesOperationCompleted, userState);
        }
        
        private void OnCreateFontCodesOperationCompleted(object arg) {
            if ((this.CreateFontCodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFontCodesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateCololerCodesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CreateFontCodesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591